name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build all-in-one HTML
        run: npm run build

      - name: Prepare release assets
        run: |
          cd dist
          mv index.html cli-proxy-api-management-center.html
          ls -lh cli-proxy-api-management-center.html

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/cli-proxy-api-management-center.html
          body: |
            ## CLI Proxy API Management Center - ${{ github.ref_name }}

            ### Download and Usage
            1. Download the `cli-proxy-api-management-center.html` file
            2. Open it directly in your browser
            3. All assets (CSS, JavaScript, images) are bundled into this single file

            ### Features
            - Single file, no external dependencies required
            - Complete management interface for CLI Proxy API
            - Support for local and remote connections
            - Multi-language support (Chinese/English)
            - Dark/Light theme support

            ---
            🤖 Generated with GitHub Actions
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
